### ISSUE TITLE
split_by_length_of_utterances is no longer available in audiomate

### ISSUE THREAD

**Issue by TheLexoPlexx** [AASHISHAG/deepspeech-german#10]
...and therefore results in:
`AttributeError: 'Splitter' object has no attribute 'split_by_length_of_utterances`

Possible fix could be replacing it with [split](https://audiomate.readthedocs.io/en/latest/reference/subset.html#audiomate.corpus.subset.Splitter.split). That worked for me at least.

Correction for `deepspeech-german/pre-processing/prepare_data.py` would be:
`splits = splitter.split(proportions={'train': 0.7, 'dev': 0.15, 'test': 0.15}, separate_issuers=True)`

**Comment by AASHISHAG** [comment]
Thank you, for pointing out. The other possible fix is reverting to older version of audiomate.

**Comment by AASHISHAG** [comment]
The correct audiomate version suited for current scripts is `audiomate==3.0.0`

In case you happen to use the latest version correct the scripts according to @TheLexoPlexx comment. 

Closing the issue.
