### ISSUE TITLE
Your Tuda Results

### ISSUE THREAD

**Issue by DanBmh** [AASHISHAG/deepspeech-german#11]
I think i found the reason why my Tuda results are much worse than the results in your paper. It's because of the random splitting. I switched to the splitting suggested by Tuda some time ago, for better comparability with some other papers.

As you write in your paper, each tuda sample was recorded with 4 different microphones. If you split the data random, instead of the suggested splitting, you will get a lot of test samples where a sample with the same transcription is already in the training dataset, only recorded with a different microphone.

Training with random split resulted in a WER of 0.09, while training with the same parameters but with correct splitting only has 0.42 WER.

I think this also has a strong influence on all of the other trainings with combined datasets including Tuda.

**Comment by AASHISHAG** [comment]
True. I think I also pointed the variation in WER due to random splits in my earlier comments. But your hypothesis is correct. We have discussed this along with other problems in our next paper.
