### ISSUE TITLE
Use pre-trained deepspeech english model with 8khz audio files

### ISSUE THREAD

**Issue by MittalShruti** [AASHISHAG/deepspeech-german#13]
Hi Aashish,
Thanks for the repo. Great work.

I want to use deepspeech pre-trained model (on english). But i have 8khz audio files. One option is I upsample the audio files to 16khz and then use the pretrained model (0.6.1). 

Would you know any other method where i can still use the 8khz audio files with the pre-trained deepspeech model?

**Comment by AASHISHAG** [comment]
@MittalShruti : The current DeepSpeech (v.0.6.0 and before) supports only 16kHz of audio files. The best solution, as you have already mentioned, is to up-sample the audio clips.
