### ISSUE TITLE
Create a german model for DeepSpeech 0.7

### ISSUE THREAD

**Issue by verloka** [AASHISHAG/deepspeech-german#14]

**Comment by DanBmh** [comment]
You can find one in [my fork](https://github.com/DanBmh/deepspeech-german)

**Comment by AASHISHAG** [comment]
@verloka : We are working on it and will release it soon.

**Comment by glor** [comment]
Whats's the status on this? What does soon mean?

**Comment by AASHISHAG** [comment]
@glor 

In one to two weeks. v0.7.4.
