### ISSUE TITLE
Request for providing a pretrained model

### ISSUE THREAD

**Issue by CobraCalle** [AASHISHAG/deepspeech-german#17]
Hello,

at first: thank you very much for your effort to provide this highly automated train script.

Sadly I`m a real Windows guy and my Linux skills are very "limited". I`ve installed Debian on Windows and tried to get this up and running, but it looks like this will not work on linux on windows (the installation of prerequisites fails)... And setting up a whole new Linux system feels like a little bit overhead.

Would it be possible to provide a pre trained model for German language?

Thank you very much

Carl

**Comment by AASHISHAG** [comment]
@CobraCalle : Please scroll to the bottom of the ReadMe. We have provided pre-trained model for both v0.5 and v0.6.

**Comment by CobraCalle** [comment]
Sorry I missed that... It's already late... 🤦‍♂️😁

**Comment by AASHISHAG** [comment]
I hope you got the model working. Closing this issue.
