### ISSUE TITLE
For which platform has the code been developed?

### ISSUE THREAD

**Issue by Jane333** [AASHISHAG/deepspeech-german#20]
Hello,

I’m trying to execute `test_model.sh` but keep running into version problems. The scripts called by `test_model.sh` keep trying to use a quite old version of ds_ctcdecoder which is not installable on any of the platforms I’ve tried so far. Using a newer version of ds_ctcdecoder leads to one error after another.
Using DeepSpeech 0.6.0 instead of the default 0.5.0 also leads to errors.

Could you tell me on which platform it is possible to execute this code? I have tried Ubuntu 18.04, a tensorflow 1.13.1 docker container, and a deepspeech docker container by Mozilla so far, all to no avail.

Running the rest of the code in the README works fine using a conda environment with tensorflow-gpu 1.13.1.
The problems only occur when I try to run `test_model.sh`.

Thank you for your help!

**Comment by AASHISHAG** [comment]
I would recommend you to use the docker setup that I have mentioned in our other repository to build the environment to fix ds_ctcdecoder error. Please note it's based on v0.6.0 and for swiss-german, and you would still need to pre-process the dataset separately (in case you are training the model). Testing the model should work fine.

https://github.com/AASHISHAG/deepspeech-swiss-german#requirements

**Comment by Jane333** [comment]
Thank you! I followed the instructions you pointed me to, replacing "v0.6.0" by "v0.5.0" everywhere - now I'm able to use the pre-trained German models in that docker container as well as train my own, like I originally intended.
