### ISSUE TITLE
Deutsche Groß-, und Kleinschreibung

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [AASHISHAG/deepspeech-german#23]
Was müßte geändert werden, damit Satzzeichen und deutsche GuKschreibung integriert werden?
Antwort bitte auf Deutsch.

**Comment by zesch** [comment]
Das ist schwierig ins ASR-Modell selbst zu integrieren.
Würde man üblicherweise als post-processing implementieren.

**Comment by AASHISHAG** [comment]
Hi @ErfolgreichCharismatisch: I hope your issue is resolved. Closing this issue.

**Comment by ErfolgreichCharismatisch** [comment]
> Das ist schwierig ins ASR-Modell selbst zu integrieren.
> Würde man üblicherweise als post-processing implementieren.

Gibt es da bewährte Methoden?

**Comment by zesch** [comment]
in der theorie mittels statistischem language model aber mir sind keine direkt nutzbaren Implementierungen bekannt
