### ISSUE TITLE
Newer models?

### ISSUE THREAD

**Issue by RobinRS** [AASHISHAG/deepspeech-german#25]
Hey,

first of all: Many thanks for all the efforts from everyone until now.

I'm not that good with all the command line stuff but I have powerful servers for rendering with blender.
Would there be the option for getting a really simple instruction for creating / training the German model?
(Preferable a shell script for just starting on a Linux server?)

Many thanks
Robin

**Comment by AASHISHAG** [comment]
Hi Robin, please refer to the script from one of my colleague. This is the best I can do. Cheers!

Link: https://github.com/AASHISHAG/deepspeech-paper/blob/master/training.sh

**Comment by RobinRS** [comment]
Perfect. Many thanks 👍
