### ISSUE TITLE
DeepSpeech 0.9?

### ISSUE THREAD

**Issue by Matthias84** [AASHISHAG/deepspeech-german#26]
Hi, there is DS EN 0.9 available, which also change some details on the model architecture:
https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.0
There is also the CommonVoice Dataset  by 2020-06-22 shipping with 750hrs (690hrs confirmed) audio files for training:
https://commonvoice.mozilla.org/de/datasets

Do you think you could give it a try to update?

**Comment by AASHISHAG** [comment]
Great. Thanks for sharing. Will try to release it soon.

**Comment by AASHISHAG** [comment]
@Matthias84: The model is now released. 

Closing the ticket.

**Comment by blacktoby** [comment]
The model is released, but there is no .pbmm file in it. Can we get the file, too?

**Comment by AASHISHAG** [comment]
@blacktoby : I have uploaded the model. However, I haven't tested it, so I cannot guarantee.

You can also refer to the instructions on README: https://github.com/mozilla/DeepSpeech/blob/ad0f7d2ab7f4505d870fb2eaf25373b788d1d938/doc/TRAINING.rst
