### ISSUE TITLE
Scorer file for 0.9 release

### ISSUE THREAD

**Issue by CobraCalle** [AASHISHAG/deepspeech-german#28]
Hello,

I`m relatively new to DeepSpeech, I`m trying to replace the online speech recognition I use at the moment with DeepSpeech, but the results I`m getting at the moment are very far away for (for example Azure Speech Recognition). Perhaps I´m feeding the data in the wrong format or something like that. 

What I`ve learned so far is that there "could be" a language dependent scorer file, but I can`t find one for the 0.9 version. Can you provide that file? Or is this not required?

Can you provide some information about the required input? At the moment I`m using wav-data at 16000 samples per seconds, 16 bit sample size and one channel... is that correct?

Thank you very much for your help

Carl

**Comment by AASHISHAG** [comment]
Hello @CobraCalle 

> the results I`m getting at the moment are very far away for (for example Azure Speech Recognition)

AA: I would not compare the quality of Azure's ASR with DeepSpeech. The Azure system is trained on thousands hours of dataset. On the contrary, German DeepSpeech model (we trained) is build on ~3-5% of dataset. 
The system should further be trained on more dataset to get realistic performance.

> What Ive learned so far is that there "could be" a language dependent scorer file, but I cant find one for the 0.9 version. Can you provide that file? Or is this not required?

AA: Sure. I would upload it by tomorrow EOD.

> Can you provide some information about the required input? At the moment I`m using wav-data at 16000 samples per seconds, 16 bit sample size and one channel... is that correct?

AA: Yes

**Comment by AASHISHAG** [comment]
Resolved. Closing the ticket.
