### ISSUE TITLE
loading output_graph.tflite deepspeech-tflite result in segmentation fault

### ISSUE THREAD

**Issue by kaoh** [AASHISHAG/deepspeech-german#29]
When loading the tflite version in `deepspeech-tflite` version 0.9.2 and also 0.9.0 I get an segmentation fault SIGSEGV. Can this be replicated?

~~~python
from deepspeech import Model

model = 'output_graph.tflite'
ds = Model(model)
~~~

What could be the issue? I do not see any stacktrace or useful information how to find the source of the problem.

**Comment by AASHISHAG** [comment]
This is something to do with the deepspeech pip dependency, not with the model in general. I would recommend to please route the query directly to Mozilla DeepSpeech team.

There were some discussion on this issue before "https://discourse.mozilla.org/t/android-tflite-model-inference-issues/35173"

It might give you some hint.

**Comment by kaoh** [comment]
OK, I will reach out to them. But in general after generating the tflite model with your toolchain it was working in your tests?

**Comment by AASHISHAG** [comment]
I never happen to test any of the models for the current release. So, won't be able to say much. 

But, I have provided checkpoints, so the model can be re-generated anytime. However, it is unlikely the generated model has issues, it just the configuration issues because of which you are unable to use the model.

**Comment by koh-osug** [comment]
When re-exporting the tflite model with:

~~~
../venv_tools/bin/python DeepSpeech.py --export_tflite --export_dir . --alphabet_config_path=deepspeech-german/alphabet.txt --checkpoint_dir=deepspeech-german
~~~

The segmentation fault is gone. Maybe you can contribute to the opened deepspeech issue above and look again into your build chain. Something seems to be not functional or simply the uploaded tflite file is corrupt?

**Comment by AASHISHAG** [comment]
Hi, thank you for pointing it. Could you please provide the link to the model? I can then replace the model old tflite model.

**Comment by koh-osug** [comment]
Sure, here is it: https://drive.google.com/file/d/13JrVFD66bAhQ2NCTSRBuuqfAYX6FdA1N/view?usp=sharing

But I'm not convinced by the result. The interference takes about 7 secons in contrast to 1 second before and it does not detect anything at all. I created a custom kenml scorer focusing on a tiny domain and actually just recognizing a stop word would be sufficient, but the recognition is 0%. When not using the scorer the result are much better, but still my keyword is not detected anymore with a good enough rate. I'm wondering how a scorer can worsen the recognition in such a way.

**Comment by AASHISHAG** [comment]
> Results are convicing (at least for my voice).

Good to hear such convincing words. :)

I never happen to use tflite model myself. But in case you find more information on the parameters, please contribute to the repository (for the benefit of the open-source community in general)

**Comment by terler188** [comment]
Thanks for your input @koh-osug =)

I run into the same error. Using the 0.7.4 tflite file and the original tflite files from deepspeech works. Now, using your shared tflite file also works perfectly. Maybe this file could be exchanged in the original google drive folder?

**Comment by AASHISHAG** [comment]
@terler188 : Thank you for reminding. I have now uploaded the tflite model to the drive. Thanks to @koh-osug

**Comment by kaoh** [comment]
Maybe there is an issue with the tool chain and it is using an old transformer to tflite. A python test trying to recognize a sample would detect this kind of issue to prevent buggy releases. This could be done with the full model and the tflite model.

**Comment by AASHISHAG** [comment]
@kaoh : Pull requests are welcome 😉

**Comment by kaoh** [comment]
I haven't found a script with `python DeepSpeech.py --export_tflite ...` used for the TFLite generation and this step is not documented in the README. Should I add this script or do you have it locally so that it can be included to match always the local DeepSpeech installation?

**Comment by AASHISHAG** [comment]
**DeepSpeech.py** is the main file for running DeepSpeech. It's a part of Mozilla DeepSpeech's codebase, and therefore:
1. It cannot be run explicitly.
2. It changes with every release (expected).
And thus cannot be part of this repository. 

However, I would love to accept pull-requests for any script that's not the part of Mozilla's codebase.  And you can always submit a request to improve the ReadMe. 😉

**Comment by kaoh** [comment]
I can see now in Google drive two versions: `output_graph_from_koh-osug.tflite` and `output_graph.tflite`. I guess this is confusing for users, if the `output_graph.tflite` is causing a segfault (or is only working with older version) why keeping it and not overwriting it with `output_graph.tflite`?

**Comment by AASHISHAG** [comment]
Sure. I have removed it.

**Comment by kaoh** [comment]
I will close this one now. I will create a pull request soon for some updates for the scripts and the README. The steps from README are not working anymore with the necessary steps for DeepSpeech 0.9.3. I  had also add DeepSpeech and KenLM as submodules, which make the checkout more straight forward and is always using the version which was tested against this project.

**Comment by AASHISHAG** [comment]
Awesome. Looking forward to it.
