### ISSUE TITLE
Loading pretrained model

### ISSUE THREAD

**Issue by sadia95** [AASHISHAG/deepspeech-german#30]
Hi, I want to use your pretrained model for German. I am not really sure how to use it on windows. And is it going to work on a normal computer?

**Comment by AASHISHAG** [comment]
Hi, please check our other repository for running deepspeech on a browser (of course it would work on windows).

Link: https://github.com/AASHISHAG/DeepSpeech-API

**Comment by sadia95** [comment]
Actually I want to use your pretrained model and further fine tune it on my dataset.

**Comment by AASHISHAG** [comment]
You can try installing Windows Subsystem for Linux and give it a shot. But you would definitely need GPU's to efficiently train the system. 
However, I would still recommend training on Linux.

**Comment by AASHISHAG** [comment]
I am hoping the issue is resolved. Closing the ticket.
