### ISSUE TITLE
Qualität der Erkennung

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [AASHISHAG/deepspeech-german#34]
Bzgl. transcribe.py
Kann man bei der Erkennung auch die Selbstsicherheit, also confidence, der Erkennung angeben, damit ich die mit niedriger Ss Erkannten gezielt überprüfen kann?

**Comment by AASHISHAG** [comment]
You can check modifying the aggressiveness at https://github.com/mozilla/DeepSpeech/blob/master/transcribe.py#L163

This would make your model more robust to noise.

**Comment by ErfolgreichCharismatisch** [comment]
Ja, doch ich frage nach einem Wert, der mir zeigt, wie sicher der Algorithmus ist, daß die Umsetzung stimmt.

**Comment by AASHISHAG** [comment]
The current model release was trained with default hyper-parameters. We have left up to the community to test and further optimize it. Feel free to send a pull request if you happen to optimize the current model.
