### ISSUE TITLE
WER results for newer models

### ISSUE THREAD

**Issue by oliverguhr** [AASHISHAG/deepspeech-german#36]
Hi,
first of all - thank you for your work. Are there any WER results for the newer models aviable, that you released after the initial paper? 

Best Regards,
Oliver

**Comment by AASHISHAG** [comment]
Hi, I don't have exact numbers for the current model release. However, I plan to do it from next.

**Comment by oliverguhr** [comment]
Thanks! Next release is v0.10?

**Comment by AASHISHAG** [comment]
> Thanks! Next release is v0.10?

Yes.
