### ISSUE TITLE
Dependency conflict with numpy

### ISSUE THREAD

**Issue by newcode3000** [AASHISHAG/deepspeech-german#38]
When executing the command
pip3 install -r python_requirements.txt
I get the following message:

`ERROR: Cannot install -r python_requirements.txt (line 12), -r python_requirements.txt (line 4), -r python_requirements.txt (line 47), -r python_requirements.txt (line 54), -r python_requirements.txt (line 56), h5py==2.10.0, keras-preprocessing==1.1.2, librosa==0.7.2, numba==0.49.1, numpy==1.18.1, opt-einsum==3.3.0, resampy==0.2.2 and scipy==1.4.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.18.1
    audiomate 6.0.0 depends on numpy==1.18.1
    ds-ctcdecoder 0.9.3 depends on numpy>=1.14.5
    h5py 2.10.0 depends on numpy>=1.7
    keras-preprocessing 1.1.2 depends on numpy>=1.9.1
    librosa 0.7.2 depends on numpy>=1.15.0
    numba 0.49.1 depends on numpy>=1.15
    opt-einsum 3.3.0 depends on numpy>=1.7
    resampy 0.2.2 depends on numpy>=1.10
    scikit-learn 0.24.0 depends on numpy>=1.13.3
    scipy 1.4.1 depends on numpy>=1.13.3
    tensorboard 2.4.0 depends on numpy>=1.12.0
    tensorflow 2.4.0 depends on numpy~=1.19.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies`

So, audiomate 6.0.00 requires numpy==1.18.1 and  tensorflow 2.4.0 depends on numpy~=1.19.2.

I tried installing
pip install audiomate tensorflow
this succeeds with tensorflow 2.3.2 being installed. But I don't know whether this would work with deepspeech-german .

Any suggestions for resolving this ?

**Comment by AASHISHAG** [comment]
I know users are using Tensorflow==v1.15.4 with current dependencies. This might solve the conflict.

**Comment by AASHISHAG** [comment]
Assuming issue is resolved. Closing it.

**Comment by newcode3000** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Hi,sorry that I didn't reply. Normally I say at least thanks if somone replys on my question.In this case I has suddenly other problems and I forgot about the topic.Regards,Florian

Aashish Agarwal schrieb am 25.03.2021 15:56 (GMT +01:00):

Closed #38.
