### ISSUE TITLE
DeepSpeech model used

### ISSUE THREAD

**Issue by cli0** [AASHISHAG/deepspeech-german#4]
Hello guys,

In your paper you say that this model was trained using deepspeech 0.5.0 but in the python requirements it says:  `deepspeech==0.2.0a8`.

How does this work then?

**Comment by AASHISHAG** [comment]
Good catch. We don't need python dependency for deepspeech for training the model. This might have got added from our earlier experiments. I have updated the (python_requirements.txt)[https://github.com/AASHISHAG/deepspeech-german/blob/master/python_requirements.txt]
