### ISSUE TITLE
Pbmm and scorer file

### ISSUE THREAD

**Issue by Xx-KaAzZ-xX** [AASHISHAG/deepspeech-german#50]
Hi, 

I simply looking for a pbmm and scorer file for the German translation, it drives me crazy because I could found it in french https://github.com/Common-Voice/commonvoice-fr/releases, it's working like a charm but I don't find the German equivalent.

My poor computing power and network bandwith (to download CV datasets for example) don't allow me to train my model and honestly, I don't want to (lazy like a good IT guy :) 

Someone probably did upload those files somewhere already, any information would be appriciated !

Cheers :)

**Comment by domcross** [comment]
Links to the pretrained german models can be found at the end of README.md:
https://github.com/AASHISHAG/deepspeech-german#trained-models

**Comment by Xx-KaAzZ-xX** [comment]
I saw "English" so I didn't try, I tried and it worked... So stupid of me, sry ! Thx
